{{- if .Values.database.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: sistema-matricula-dev-db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sistema-matricula.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.database.user | quote }}
  password: {{ .Values.database.password | quote }}
  host: {{ .Values.database.host | quote }}
  port: {{ .Values.database.port | quote }}
  database: {{ .Values.database.name | quote }}
{{- end }}
