{{- if .Values.database.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: sistema-matricula-{{ .Values.env }}-db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "sistema-matricula.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_USER: {{ .Values.database.user | quote }}
  MYSQL_PASSWORD: {{ .Values.database.password | quote }}
  MYSQL_HOST: {{ .Values.database.host | quote }}
  MYSQL_PORT: {{ .Values.database.port | quote }}
  MYSQL_DATABASE: {{ .Values.database.name | quote }}
{{- end }}