apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sistema-matricula.fullname" . }}
  labels:
    {{- include "sistema-matricula.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sistema-matricula.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        redeploy-timestamp: "{{ now | unixEpoch }}"
      labels:
        {{- include "sistema-matricula.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
          - containerPort: 8000
        env:
          - name: MYSQL_DATABASE
            value: {{ .Values.database.name | quote }}
          - name: MYSQL_USER
            value: {{ .Values.database.user | quote }}
          - name: MYSQL_PASSWORD
            value: {{ .Values.database.password | quote }}
          - name: MYSQL_HOST
            value: "mysql"
          - name: DJANGO_SETTINGS_MODULE
            value: sistema_academico.settings
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
