{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "sistema-matricula.fullname" . }}-migrations
  labels:
    {{- include "sistema-matricula.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: {{ .Values.migrations.backoffLimit }}
  template:
    metadata:
      labels:
        job: migrations
    spec:
      restartPolicy: Never
      containers:
      - name: migrations
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        command:
          - sh
          - -c
          - |
            echo "Aguardando MySQL...";
            sleep 10;
            python manage.py makemigrations;
            python manage.py migrate --noinput;
            python manage.py collectstatic --noinput;
            echo "✔ Migrations concluídas!"
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ include "sistema-matricula.fullname" . }}-db-secret
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "sistema-matricula.fullname" . }}-db-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "sistema-matricula.fullname" . }}-db-secret
              key: MYSQL_PASSWORD
        - name: DJANGO_SETTINGS_MODULE
          value: sistema_academico.settings
{{- end }}