apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sistema-matricula.fullname" . }}-db-secret
  labels:
    {{- include "sistema-matricula.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_DATABASE: {{ .Values.database.name | b64enc | quote }}
  MYSQL_USER: {{ .Values.database.user | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.database.rootPassword | b64enc | quote }}
  MYSQL_HOST: {{ .Values.database.host | quote }}