# Ambiente de Produção
replicaCount: 3

fullnameOverride: sistema-matricula-prod

image:
  repository: ghcr.io/marcusxdm/sistema-matricula-ifal-django
  tag: "prod-latest"
  pullPolicy: Always

debug: false

service:
  type: ClusterIP
  port: 8000

database:
  port: 3306
  host: mysql-prod
  name: sistema_matricula_prod
  user: prod_user
  password: prod_password_456
  rootPassword: prod_root_password_456
  secret:
    enabled: true

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: sistema-matricula.local
      paths:
        - path: /
          pathType: Prefix
          port: 8000

migrations:
  enabled: true
  backoffLimit: 3

gitCommit: ""