# Ambiente de Desenvolvimento
replicaCount: 1

image:
  tag: "develop-{{ .Values.gitCommit }}"
  pullPolicy: Always

debug: true

service:
  type: NodePort

database:
  host: mysql
  name: sistema_matricula_dev
  user: dev_user
  password: dev_password_123
  rootPassword: dev_root_password_123
  secret:
    enabled: true

ingress:
  enabled: true
  hosts:
    - host: dev.sistema-matricula.local
      paths:
        - path: /
          pathType: Prefix

gitCommit: ""