# Valores padrão
replicaCount: 1

image:
  repository: ghcr.io/marcusxdm/sistema-matricula-ifal-django
  tag: "develop"   # <-- coloque a tag real que existe no GHCR
  pullPolicy: Always

debug: false

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: sistema-matricula.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Configuração do banco de dados
database:
  port: 3306
  host: mysql
  name: sistema_matricula_dev
  user: dev_user
  password: dev_password_123
  rootPassword: dev_root_password_123
  secret:
    enabled: true

# Job de migrations
migrations:
  enabled: true
  backoffLimit: 3