name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare dynamic tag
        id: prepare-tags
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)

          # lowecase name
          IMAGE_NAME_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')

          IMAGE_TAG="${BRANCH_NAME}-${SHORT_SHA}"

          # branch variable
          if [ "$BRANCH_NAME" = "develop" ]; then
            LATEST_TAG="develop-latest"
            GITOPS_PATH="dev"
          elif [ "$BRANCH_NAME" = "main" ]; then
            LATEST_TAG="prod-latest"
            GITOPS_PATH="prod"
          else
            LATEST_TAG=""
            GITOPS_PATH=""
          fi

          echo "tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "latest-tag=${LATEST_TAG}" >> $GITHUB_OUTPUT
          echo "gitops-path=${GITOPS_PATH}" >> $GITHUB_OUTPUT
          echo "image=${{ env.REGISTRY }}/${IMAGE_NAME_LOWER}" >> $GITHUB_OUTPUT

          echo "Using image: ${{ env.REGISTRY }}/${IMAGE_NAME_LOWER}"
          echo "Using tag: $IMAGE_TAG"
          echo "Using latest tag: $LATEST_TAG"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.prepare-tags.outputs.image }}:${{ steps.prepare-tags.outputs.tag }}
            ${{ steps.prepare-tags.outputs.image }}:${{ steps.prepare-tags.outputs.latest-tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Clone GitOps repository
        if: steps.prepare-tags.outputs.gitops-path != ''
        run: |
          git clone https://github.com/marcusxdm/argocd-gitops.git gitops
          cd gitops
          git checkout main

      - name: Update Rollout manifest
        if: steps.prepare-tags.outputs.gitops-path != ''
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update image tag to ${{ steps.prepare-tags.outputs.tag }}"
          branch: main
          file_pattern: "gitops/apps/${{ steps.prepare-tags.outputs.gitops-path }}/rollout.yaml"
          commit_user_name: "github-actions"
          commit_user_email: "github-actions@users.noreply.github.com"
        env:
          IMAGE_TAG: ${{ steps.prepare-tags.outputs.tag }}
          IMAGE_NAME: ${{ steps.prepare-tags.outputs.image }}