name: CI/CD Pipeline - GitOps + Argo Rollouts

on:
  push:
    branches:
      - main
      - develop

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare dynamic tags
        id: prepare-tag
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          IMAGE_TAG="${BRANCH_NAME}-${SHORT_SHA}"
          IMAGE_NAME_LOWER=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')

          # Define latest tag dependendo do branch
          if [ "$BRANCH_NAME" = "develop" ]; then
            LATEST_TAG="develop-latest"
          elif [ "$BRANCH_NAME" = "main" ]; then
            LATEST_TAG="prod-latest"
          else
            LATEST_TAG=""
          fi

          echo "tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "image-name=${IMAGE_NAME_LOWER}" >> $GITHUB_OUTPUT
          echo "latest-tag=${LATEST_TAG}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.prepare-tag.outputs.image-name }}:${{ steps.prepare-tag.outputs.tag }}
            ${{ env.REGISTRY }}/${{ steps.prepare-tag.outputs.image-name }}:${{ steps.prepare-tag.outputs.latest-tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update rollout.yaml with new SHA tag
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          IMAGE_TAG="${BRANCH_NAME}-${GITHUB_SHA::7}"
          if [ "$BRANCH_NAME" = "develop" ]; then
            ROLLOUT_FILE="deploy/dev/rollout.yaml"
          elif [ "$BRANCH_NAME" = "main" ]; then
            ROLLOUT_FILE="deploy/prod/rollout.yaml"
          fi

          echo "Updating rollout.yaml with image tag $IMAGE_TAG"

          # Atualiza a imagem no rollout.yaml com yq
          yq -i '.spec.template.spec.containers[0].image = "ghcr.io/marcusxdm/sistema-matricula-ifal-django:'"$IMAGE_TAG"'"' $ROLLOUT_FILE

      - name: Commit and push rollout.yaml update
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add deploy/**/rollout.yaml
          git commit -m "Update rollout image to $IMAGE_TAG [skip ci]" || echo "No changes to commit"
          git push